### ISSUE TITLE
not work on openapi  3.0.3

### ISSUE THREAD

**Issue by ghost** [luckymarmot/Paw-OpenAPI3Importer#11]
i used this rep: https://github.com/tfranzel/drf-spectacular

it have a url:  http://127.0.0.1:8000/api/schema/ 

# in paw,  import error:
![image](https://user-images.githubusercontent.com/6580897/120477440-5a4bb880-c3de-11eb-9c6f-87eab6b4cfdf.png)

# in postman, import ok 

![image](https://user-images.githubusercontent.com/6580897/120477549-78b1b400-c3de-11eb-8178-7887961f6714.png)

**Comment by pongstr** [comment]
hello @stfenjobs  could you please provide an example of your schema?

**Comment by kamontat** [comment]
OpenAPI 3.0.2 didn't work as well. https://gist.github.com/kamontat/c7a7ad9ed76f9c5c423e438e88db505a

**Comment by pongstr** [comment]
> OpenAPI 3.0.2 didn't work as well. https://gist.github.com/kamontat/c7a7ad9ed76f9c5c423e438e88db505a

@kamontat  the gist doesn't seem to be a valid OpenAPI v3.0.x schema. The plugin doesn't accept fragments, but a whole document.

**Comment by mshahat** [comment]
same here, not working for me. Perhaps a good idea for Paw to complain if it can't import a specification! and if you guys could document any restrictions or known issues!   Thanks

**Comment by pongstr** [comment]
@stfenjobs @kamontat  I've stub a patch to potentially fix your issues. Please see [0.1.1-beta.2](https://github.com/luckymarmot/Paw-OpenAPI3Importer/releases/tag/0.1.1-beta.2), [Downloadable Zip
](https://github.com/luckymarmot/Paw-OpenAPI3Importer/releases/download/0.1.1-beta.2/com.luckymarmot.PawExtensions.OpenAPI3Importer.zip)

Let me know if there are any other issues, we'll try our best to get this extension stable. Thanks!

**Comment by ghost** [comment]
@pongstr  thank you  , its work  ,  but ,  the host is not my host, it show  `https://echo.paw.cloud`


my host is `http://127.0.0.1:8000 `   but  when i import , the host change to  `https://echo.paw.cloud`

**Comment by stfenjobs** [comment]
https://user-images.githubusercontent.com/6580897/122642287-3e654800-d13c-11eb-8c68-ace268749d4a.mov

**Comment by pongstr** [comment]
@stfenjobs thanks for testing right away. I might need to figure out how I can make the host a dynamic variable. But for now, you can define your document's server like so: 

```yaml
---
openapi: 3.0.2
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: "..."
servers:
  - url: 'https://petstore3.swagger.io' ## For now this will replace the default url (https://echo.paw.cloud)
```

**Comment by ghost** [comment]
@pongstr 

thank you very much
