### ISSUE TITLE
Doesn't show in the import menu (develop)

### ISSUE THREAD

**Issue by rlweb** [luckymarmot/Paw-OpenAPI3Importer#3]
I've tried with master and develop branches but within Paw it does not show as an import option:

![image](https://user-images.githubusercontent.com/173838/100605839-72902d00-3300-11eb-8d9e-a28a7ed9db26.png)

My extension list is as shown:

![image](https://user-images.githubusercontent.com/173838/100605876-7f148580-3300-11eb-8d64-afd25a917008.png)

and the command I'm using to build and send to paw

![image](https://user-images.githubusercontent.com/173838/100605914-8dfb3800-3300-11eb-9b98-5c2f43b20af7.png)

Any idea's?

**Comment by pongstr** [comment]
hey @rlweb, this has been fixed and improved, please update to the latest from `develop` branch and do the following:

```bash
## update packages
npm install  && npm run dev:mac:static

## or if you prefer yarn
yarn && yarn dev:mac:static
```

optionally, you may [follow this instruction](https://github.com/luckymarmot/Paw-OpenAPI3Importer/issues/4#issuecomment-831784892) to download and install using zip
