### ISSUE TITLE
How to use this

### ISSUE THREAD

**Issue by nerdinand** [luckymarmot/Paw-OpenAPI3Importer#4]
For those who were, like me, stuck figuring out how to use this extension, here's a guide:

1. Clone the repository
2. `npm install`
3. `npm run build`
4. Copy the `dist/com.luckymarmot.PawExtensions.OpenAPIImporter` directory to the extension directory of your Paw installation (Preferences -> Extensions -> Open Directory)

This should probably be in the README ;)

**Comment by tmclaugh** [comment]
This will probably be more straightforward.

`npm run archiveAndPaw`

**Comment by pongstr** [comment]
I think it'd be easier to download the plugin from [release section](https://github.com/luckymarmot/Paw-OpenAPI3Importer/releases), a [Zip](https://github.com/luckymarmot/Paw-OpenAPI3Importer/releases/download/0.1.0-beta/OpenAPIv3xImporter-0.1.0-beta.zip) file is available, In the preference panel, click on:

Extensions tab -> Open Extensions Directory -> Extract Zip contents there, (hit reload installed extensions if needed).
